apiVersion: v1
kind: Service
metadata:
  name: {{ include "telegraf-qnap.fullname" . }}
  labels:
    {{- include "telegraf-qnap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "telegraf-qnap.selectorLabels" . | nindent 4 }}
