name: .Docker builder

on:
  workflow_call:
    inputs:
      docker-image-name:
        required: true
        type: string
        description: Name of Container image
      docker-registry:
        required: true
        type: string
        description: Docker registry name
      docker-repository:
        required: true
        type: string
        description: Docker repository directory name
      version:
        required: true
        type: string
        description: Container image version
      context-path:
        required: false
        type: string
        default: .
        description: Context path

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
     
      - name: Login to Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker-registry }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Get build date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%m:%S')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context-path }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ inputs.docker-registry }}/${{ inputs.docker-repository }}/${{ inputs.docker-image-name }}:${{ inputs.version }},${{ inputs.docker-registry }}/${{ inputs.docker-repository }}/${{ inputs.docker-image-name }}:latest
          build-args: |
            "APP_NAME=${{ inputs.docker-image-name }}"
            "VERSION=${{ inputs.version }}"
            "BUILD_DATE=${{ steps.date.outputs.date }}"
            "TELEGRAF_VERSION=1.32.2"
            "REVISION=${{ github.sha }}"
            "REF=${{ github.ref }}"